### ISSUE TITLE
Riset Kebutuhan: Penentuan Fitur yang Dibutuhkan

### ISSUE THREAD

**Issue by Perwira-AZ** [m-rizqi/beat-task#7]
Dapat menambahkan fitur baru yang belum ada pada rencana awal atau menghapus fitur yang tidak diperlukan pada rencana awal.

**Comment by m-rizqi** [comment]
Dokumen: https://docs.google.com/document/d/1N5Runx_XAhxZWhtq9L5jRC1lSZGrMO3cGZ2ROafyszQ/edit
